### ISSUE TITLE
Produced mzML files does not follow the schema

### ISSUE THREAD

**Issue by fcyu** [gygilab/Monocle#25]
Thanks for your contribution to the community. When I am testing this tool using an outputted mzML file, neither MSFragger nor Comet can read it. A closer looking shows that it's format does not follow the schema.

Thanks,

Fengchao

**Comment by mammmals** [comment]
Hi Fengchao,
Thanks for letting us know. Is there any indication of what params/nodes are violating the schemas when you run the Monocle output through MSFragger/Comet?
Thanks,
Devin

**Comment by fcyu** [comment]
Hi Devin,

The incorrect position of `</cvList>` was the first one we spotted. After correcting that by editing the mzML file, there was another error thrown from MSFragger and Comet. So, it looks like there are multiple ones and we don't have time to find all of them.

Best,

Fengchao

**Comment by mammmals** [comment]
OK, we'll go through and track those down ASAP.
Best,
Devin

**Comment by rrad42** [comment]
Hi Fengchao,

I've updated Monocle to output mzML files that now seem to validate against the schema.  I've also tried a search with the latest release of comet and it produces reasonable-looking results, but I havent tried MSFragger.  Please give it another try and let us know if there are any more issues.

Ramin

**Comment by fcyu** [comment]
Hi Ramin,

Thanks for your fast fix. It works.

Best,

Fengchao
