### ISSUE TITLE
Produced mzxml files doesn't read by Proteome Discoverer or MaxQuant

### ISSUE THREAD

**Issue by RSN4ever** [gygilab/Monocle#26]
Dear Developers,

Thank you so much for creating this important tool in correcting monoisotopic peak correction which definitely has huge implications on MS-based proteomic result outputs. The produced mzxml  files by monocle were unable to initiate a search by Proteome Discoverer. MaxQuant does complete the search but gives just 28 IDs with a very low Andromeda score. I appreciate if you could fix this issue.

Best,
Raja

**Comment by rrad42** [comment]
Hi Raja

The latest now produces mzXMLs that validate against the schema and are searchable with comet.

I dont have access to PD right now, and I can't find an mzXML that works with MaxQuant.  Files converted with msconvert or raw converter dont seem to work with MaxQuant either.  If you have more information about what could be wrong, or if you have an mzXML file that works in MaxQuant, please share and I'll try to debug the issue further.

Ramin
