### ISSUE TITLE
Monocle converted mzml files make FragPipe crash at the LFQ step

### ISSUE THREAD

**Issue by Peer2011** [gygilab/Monocle#30]
Dear developer of Monocle,

We tried to use Monocle for Raw file conversion before searching and quantifying our files via Fragpipe. Everything goes fine until the step of quantification when Ionquant tries to write the tables. Here, Monocle converted mzml Files make Ioquant crash with the following error message. Any idea how to solve this problem. We converted the raw files with standard settings. Is there any more detailed documentation about Monocle. Could not find many information on how to use it besides the readme file. Is there any way to run Monocle on multiple files with a more simpler command (*.raw ???). Thanks a lot for your efforts. 

Best, Peer

**Comment by rrad42** [comment]
Sorry I neglected to hit publish on the new version.  There is also a prebuilt Monocle UI release now (thanks to Devin).  I updated the releases and the version numbers will look a little different, but head to the releases page to see the new downloads.

The UI version actually shows a window, allows you to convert multiple files at once, and you can drag and drop them in, so you'll likely find it more convenient.

**Comment by mammmals** [comment]
The multi-file CLI will require a bit more work to build and test, though the UI can currently do this using the `FileProcessor` functionality. I opened a new issue for the functionality: #32
